# Site settings
title: Progress2020
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We're working to match organizations with volunteers to keep our country together and progress towards 2020.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://progress2020.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  progress2020

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
